// Domain model for the AI Financial Coach (V3).
// All money values are demo values (the source statement amounts divided by 10) and
// contain no PII.

export type GoalCategory =
  | 'spending_control'
  | 'savings'
  | 'debt'
  | 'financial_hygiene'
  | 'benefits_income'

export type GoalDifficulty = 'soft' | 'normal' | 'ambitious'

export type GoalStatus =
  | 'suggested'
  | 'accepted'
  | 'in_progress'
  | 'completed'
  | 'replaced'
  | 'paused'

export type GoalProgressType = 'money_saved' | 'spend_limit' | 'steps' | 'binary'

export type GoalPeriod = 'week' | 'month'

export type Confidence = 'low' | 'medium' | 'high'

/** A reusable goal blueprint from the catalog. */
export type GoalTemplate = {
  id: string
  category: GoalCategory
  title: string
  description: string
  progressType: GoalProgressType
  defaultPeriod: GoalPeriod
  configurableFields: string[]
  examples: string[]
  /** Short one-liner shown on the catalog card. */
  exampleLabel: string
  /** Recommended defaults (difficulty = normal) used to instantiate a UserGoal. */
  defaults: {
    targetAmount?: number
    limitAmount?: number
    stepsTotal?: number
    relatedCategoryId?: string
    deadlineDays?: number
  }
  /** Whether this goal may be AUTO-suggested for the given data. Manual selection
   * is never gated. Missing → always eligible. */
  relevance?: (s: DataSignals) => boolean
}

/** A concrete, instantiated goal the user can accept and track. */
export type UserGoal = {
  id: string
  templateId: string
  title: string
  description: string
  category: GoalCategory
  progressType: GoalProgressType
  difficulty: GoalDifficulty
  status: GoalStatus
  period: GoalPeriod
  // money_saved
  targetAmount?: number
  currentAmount?: number
  // spend_limit
  limitAmount?: number
  spentAmount?: number
  // steps
  stepsTotal?: number
  stepsCompleted?: number
  // binary
  done?: boolean
  deadline?: string
  relatedCategoryId?: string
  recommendedReason: string
  confidence: Confidence
  aiExplanation: string
}

export type DemoTransaction = {
  id: string
  date: string
  direction: 'income' | 'expense'
  amount: number
  categoryId: string
  categoryName: string
  merchant: string
  description: string
  isRecurring?: boolean
  isPotentialTransferToSelf?: boolean
  isNeedsClarification?: boolean
}

export type ChatRole = 'user' | 'assistant'
export type ChatMessage = { id: number; role: ChatRole; text: string; loading?: boolean }

export type AnalysisStatus =
  | 'idle'
  | 'analyzing'
  | 'questions'
  | 'summary'
  | 'goals'
  | 'progress'

/** Tone of an LLM "year-in-review" conclusion card. */
export type CardTone = 'good' | 'neutral' | 'watch'

export type SummaryCard = {
  id: string
  title: string
  body: string
  tone: CardTone
}

export type FinancialCoachState = {
  analysisStatus: AnalysisStatus
  userAnswers: Record<string, string>
  /** Clarifying questions for the current run — generated by the LLM (or static fallback). */
  analysisQuestions: ClarifyingQuestion[]
  /** LLM conclusion cards shown on the summary screen. */
  summaryCards: SummaryCard[]
  suggestedGoals: UserGoal[]
  activeGoals: UserGoal[]
  chatMessages: ChatMessage[]
  /** "Почему этот план" — cohesive explanation (gpt-5.5). */
  planExplanation: string
  /** Audit call in flight (analyzing screen). */
  questionsLoading: boolean
  /** Goal-selection call in flight (summary → goals). */
  resultsLoading: boolean
  /** True when a call fell back to the deterministic path. */
  analysisError: boolean
}

export type MonthlyAggregate = {
  month: string
  income: number
  expenses: number
  balance: number
}

export type SpendingBucket = {
  id: string
  name: string
  /** Short label for use inside goal titles, e.g. "маркетплейсы". */
  shortLabel: string
  amount: number
  operationsCount: number
  insight: string
}

export type FinancialSummary = {
  periodStart: string
  periodEnd: string
  periodLabel: string
  operationsCount: number
  income: number
  expenses: number
  balance: number
}

export type ClarifyingQuestion = {
  id: string
  question: string
  hint?: string
  options: { value: string; label: string }[]
}

/** Description-derived sub-split of an ambiguous spending bucket (transfers / «Другое»). */
export type BucketBreakdownItem = {
  key: string
  label: string
  amount: number
  operationsCount: number
  /** false = movement between own accounts / not real spending. */
  isSpending: boolean
}

/** Signals derived from the data, used to gate which goals may be auto-suggested. */
export type DataSignals = {
  hasFlexibleSpend: boolean
  hasRegularIncome: boolean
  balanceNegative: boolean
  otherLarge: boolean
  hasSubscriptions: boolean
  hasDebt: boolean
  hasCreditCard: boolean
}
